# Generated by Django 5.2.7 on 2025-10-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='malzeme',
            name='seri_no',
            field=models.CharField(blank=True, db_index=True, default='YOK', max_length=100, null=True),
        ),
    ]
