# Generated by Django 5.2.7 on 2025-10-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayim', '0002_malzeme_seri_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='sayimdetay',
            name='latitude',
            field=models.CharField(blank=True, default='YOK', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sayimdetay',
            name='loc_hata',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sayimdetay',
            name='longitude',
            field=models.CharField(blank=True, default='YOK', max_length=50, null=True),
        ),
    ]
