# Generated by Django 5.2.7 on 2025-10-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayim', '0003_sayimdetay_latitude_sayimdetay_loc_hata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sayimemri',
            name='ad',
            field=models.CharField(max_length=255, verbose_name='Sayım Emri Adı'),
        ),
    ]
