# render.yaml (render.yaml dosyasının içeriği)
services:
  - type: web
    name: Stok-1
    env: python
    buildCommand: 'pip install -r requirements.txt'
    startCommand: '/bin/bash -c "apt-get update && apt-get install -y libpq-dev && python manage.py collectstatic --noinput && python manage.py migrate && /usr/bin/env PATH=\'/opt/render/.local/bin:$PATH\' python -m gunicorn stock_project.wsgi --log-file -"'
    
    envVars:
      - key: PORT
        value: "10000"