services:
  - type: web
    name: Stok-1
    env: python
    buildCommand: 'pip install -r requirements.txt'
    
    # Yeni: Dağıtım aşamasında Django komutlarını çalıştır
    preRunCommand: 'apt-get update && apt-get install -y libpq-dev tesseract-ocr && python manage.py collectstatic --noinput && python manage.py migrate' 
    
    # KRİTİK: gunicorn'u PATH sorunlarını es geçerek Python modülü olarak çağır
    startCommand: 'python -m gunicorn stock_project.wsgi'
    
    envVars:
      - key: PORT
        value: "10000"