services:
  - type: web
    name: Stok-1
    env: python
    buildCommand: 'pip install -r requirements.txt'
    preRunCommand: 'python manage.py collectstatic --noinput && python manage.py migrate' 
    startCommand: '/usr/bin/env PATH="/opt/render/.local/bin:$PATH" gunicorn stock_project.wsgi'
    envVars:
      - key: PORT
        value: "10000"