services:
  - type: web
    name: Stok-1
    env: python
    buildCommand: 'pip install -r requirements.txt'
    preRunCommand: 'python manage.py collectstatic --noinput && python manage.py migrate' 
    
    # START COMMAND'A PATH'İ EXPORT EDEN GÜVENLİ KOMUT
    startCommand: 'export PATH=/usr/local/bin:$PATH && export PYTHONPATH=/opt/render/project/src && gunicorn stock_project.wsgi'
    
    envVars:
      - key: PORT
        value: "10000"