services:
  - type: web
    name: Stok-1
    env: python
    buildCommand: 'pip install -r requirements.txt'
    preRunCommand: 'python manage.py collectstatic --noinput && python manage.py migrate' 
    
    # START COMMAND'I PATH'i es geçen PYTHON MODÜL ÇAĞRISIYLA DEĞİŞTİRİYORUZ
    startCommand: 'python -m gunicorn stock_project.wsgi'
    
    envVars:
      - key: PORT
        value: "10000"