services:
  - type: web
    name: Stok-1
    env: python
    buildCommand: 'pip install -r requirements.txt'
    
    # PreRunCommand: Tesseract ve statik dosyaları toplar. Migration buradan çıkarıldı.
    preRunCommand: 'apt-get update && apt-get install -y libpq-dev tesseract-ocr && python manage.py collectstatic --noinput'
    
    # KRİTİK: Başlangıç komutu. Sunucu başlamadan önce veritabanı güncellenir.
    # python manage.py migrate komutu başarılı olursa (&&), gunicorn başlar.
    startCommand: 'python manage.py migrate && python -m gunicorn stock_project.wsgi'
    
    envVars:
      - key: PORT
        value: "10000"