# render.yaml (SADECE BAŞLATMA KOMUTU)
services:
  - type: web
    name: Stok-1
    env: python
    buildCommand: 'pip install -r requirements.txt' # DEĞİŞMEZ
    # Start Command'dan apt-get komutlarını tamamen kaldırıyoruz:
    startCommand: 'python manage.py collectstatic --noinput && python manage.py migrate && gunicorn stock_project.wsgi'
    
    envVars:
      - key: PORT
        value: "10000"